name: imagebox
favicon: null
layout_spectrum: 0.06351463217288256
typography_spectrum: 0.5941251588519663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3032270781695843
  lightness: 0.9532586557324976
  saturation: 0.7682544477283955
  rhythmicContrast: 0.48911124211736023
purpose: []
